# Generated by Django 4.2.16 on 2025-08-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parkingrequestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingbill',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.parking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='parkingbill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.parkingbill'),
        ),
    ]
