# Generated by Django 4.2.16 on 2025-08-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_alter_parkingbill_parking_alter_payment_parkingbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='park_no',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
