# Generated by Django 4.2.16 on 2025-09-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_parking_no_parking_park_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesettings',
            name='minutes',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='timesettings',
            name='maximumTime',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='timesettings',
            name='minimumTime',
            field=models.FloatField(null=True),
        ),
    ]
