# Generated by Django 4.2.16 on 2025-09-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_timesettings_minutes_alter_timesettings_maximumtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesettings',
            name='minutes',
        ),
        migrations.AddField(
            model_name='timesettings',
            name='hours',
            field=models.FloatField(null=True, verbose_name='Number of hours'),
        ),
    ]
