# Generated by Django 4.2.16 on 2025-08-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='parking',
            new_name='parkingbill',
        ),
        migrations.AddField(
            model_name='parking',
            name='status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='parkingbill',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
