# Generated by Django 4.2.16 on 2025-08-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_rename_parking_payment_parkingbill_parking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentNo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
