# Generated by Django 4.2.16 on 2025-08-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_payment_no_payment_paymentno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=50, null=True)),
                ('originate_from_ip', models.CharField(max_length=50, null=True)),
                ('query_raw', models.TextField(null=True)),
                ('our_response_raw', models.TextField(null=True)),
                ('is_authentication', models.BooleanField(default=False)),
            ],
        ),
    ]
