# Generated by Django 4.2.16 on 2025-08-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_custpermission_module_delete_modulecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LoginLog',
                'verbose_name_plural': 'LoginLogs',
                'db_table': 'login_log',
            },
        ),
    ]
