# Generated by Django 4.2.16 on 2025-07-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211028_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custpermission',
            name='module',
        ),
        migrations.DeleteModel(
            name='ModuleCategory',
        ),
    ]
